development:
 data_dir:
   
 uniprot_base_url:
  http://uniprot.org/uniprot/ 
 websites_bbcf_dir:
 
 bbcftools_dir:
 

production:
 data_dir:
 
 uniprot_base_url:
  http://uniprot.org/uniprot/
 websites_bbcf_dir:
 
 bbcftools_dir:
 

